Feature/react router
proga-react-practice/delta-team-project pull request #1
Opened 2024-05-13 19:36 UTC by mykyta07

2024-05-14 10:56 UTC, Emil-Khalus requested changes

2024-05-14 10:56 UTC, Emil-Khalus commented on src/pages/Andrii/cards/FormResult.tsx
> +  };
please use react-hook-form validation

2024-05-14 10:56 UTC, Emil-Khalus commented on src/pages/Andrii/cards/FormResult.tsx
> +                                onChange={handleInputChange('lastName')}
you can use react-hook-form for tracking input value and errors state

2024-05-14 10:56 UTC, Emil-Khalus commented on src/pages/Layout.tsx
> +    // const theme = useTheme();
drop comment please

2024-05-14 10:56 UTC, Emil-Khalus commented on src/pages/Andrii/cards/FormResult.tsx
> +  };
you can replace it with react-hook-form

2024-05-14 10:56 UTC, Emil-Khalus commented on src/pages/Andrii/cards/FormResultMobile.tsx
> +    };
the same here

2024-05-14 11:00 UTC, Thundem commented on src/pages/Layout.tsx
> +    // const theme = useTheme();
i fixed it

2024-05-14 11:00 UTC, Emil-Khalus commented
I think this fields should be cleared after submit
![image](https://github.com/proga-react-practice/delta-team-project/assets/79042240/a9dcdf06-fc33-40b4-b85e-3d27485fca66)

2024-05-18 17:38 UTC, Emil-Khalus commented on src/pages/Andrii/cards/FormResult.tsx
> +// import { DragDropContext, Droppable, Draggable } from 'react-beautiful-dnd';
comment

2024-05-18 17:40 UTC, Emil-Khalus commented on src/pages/Andrii/forms/RentCarForm.tsx
> +                borderColor: errors[fieldName] ? "error.main" : '#bcbcbc',
hardcoded color values, please replace with colors from theme

2024-05-18 17:41 UTC, Emil-Khalus commented on src/pages/Car.tsx
> +    // console.log("EDITING INDEX", index);
comment

2024-05-18 17:41 UTC, Emil-Khalus commented on src/pages/Layout.tsx
> +            color: '#5d3f1f',
hardcoded colors

2024-05-18 17:42 UTC, Emil-Khalus approved these changes

2024-05-18 17:54 UTC, merged